In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]
b = [2, 4, 6]

# Convert lists to arrays.
array_a = np.array(a)
array_b = np.array(b)

# Perform element-wise multiplication between the arrays.
array_a * array_b

array([ 2,  8, 18])

# Basic array operations

- create an array
- indexing
- check data type 
- check dimension/shape attributs
- reshape 

In [4]:
# The np.array() function converts an object to an ndarray
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [8]:
# Arrays can be indexed.
x[-1] = 5
x

array([1, 2, 3, 5])

In [9]:
# The dtype attribute returns the data type of an array's contents.
x.dtype

dtype('int32')

In [6]:
# Arrays cast every element they contain as the same data type.
arr = np.array([1, 2, 'coconut'])
arr

array(['1', '2', 'coconut'], dtype='<U11')

In [7]:
# NumPy arrays are a class called `ndarray`.
print(type(arr))

<class 'numpy.ndarray'>


In [22]:
# Check dimension/shape
arr = np.array([1, 2, 3])
# The shape attribute returns the number of elements in each dimension
# of an array.
print(arr.shape)
# The ndim attribute returns the number of dimensions in an array.
print(arr.ndim)

(3,)
1


In [13]:
# Dimension and shape for 2D array
arr_2d = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(arr_2d.shape)
print(arr_2d.ndim)
arr_2d

(4, 2)
2


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [15]:
# 3D
arr_3d = np.array([[[1, 2, 3],
                   [3, 4, 5]],

                  [[5, 6, 7],
                   [7, 8, 9]]]
)

print(arr_3d.shape)
print(arr_3d.ndim)
arr_3d

(2, 2, 3)
3


array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [16]:
# The reshape() method changes the shape of an array.
arr_2d = arr_2d.reshape(2, 4)
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
a= np.random.rand(9).reshape(3,3)
a

array([[0.90954292, 0.40599278, 0.57090715],
       [0.43506173, 0.58758674, 0.20957278],
       [0.60010318, 0.17821083, 0.24955373]])

In [36]:
# some basic operations
arr = np.array([1, 2, 3, 4, 5])

# The mean() method returns the mean of the elements in an array.
print('the mean of array {} is :{}'.format(arr,np.mean(arr)))

# The log() method returns the natural logarithm of the elements in an array.

print('the log of array {} is {}'.format(arr,np.log(arr)))

# The floor() method returns the value of a number rounded down
# to the nearest integer.
print('the rounded down value for {} is {}'.format(8.6,np.floor(8.6)))


# The ceil() method returns the value of a number rounded up
# to the nearest integer.
print('the rounded down value up {} is {}'.format(8.6,np.ceil(8.6)))


the mean of array [1 2 3 4 5] is :3.0
the log of array [1 2 3 4 5] is [0.         0.69314718 1.09861229 1.38629436 1.60943791]
the rounded down value for 8.6 is 8.0
the rounded down value up 8.6 is 9.0


In [38]:
print('Max =', np.max(arr))
print('Min =', np.min(arr))
print('Median =', np.median(arr))
print('Std =', np.std(arr))

Max = 5
Min = 1
Median = 3.0
Std = 1.4142135623730951


# Tips
- Arrays are useful for performing element-wise operations, including arithmetic and comparisons.
- Arrays are similar to lists, but only store one type of data per array.
- Processing data stored in an array is much quicker than processing data stored in traditional lists.